apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-001
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/malhotra-jatin44/cicd-proj01.git
    targetRevision: main
    path: k8-charts/backend-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
